### ISSUE TITLE
issue00 / * - Natural number score from 0 to 10

### ISSUE THREAD

**Issue by ToJans** [ToJans/idris101#17]
First make sure Idris works.

**Comment by JefClaes** [comment]
@ToJans Which commands are you using to compile your implementation?

**Comment by ToJans** [comment]
````
idris xxx.idr -o xxx
````

As mentioned on slack: make sure you copy `winpthread-1.dll` into the same folder as your exe in order to be able to execute it.

**Comment by JefClaes** [comment]
Yes, that's what I was using, but I'm missing something "executable" no?

C:\idris\idris-win64-0.9.14.2\idris
? idris bowling.idr -o bowling
main:0:0:When elaborating an application of function run__IO:
        No such variable Main.main

**Comment by ToJans** [comment]
We should probably do this on slack, as everyone will get emails about this?
