### ISSUE TITLE
assignment #2: the bowling kata

### ISSUE THREAD

**Issue by ToJans** [ToJans/idris101#22]
As @ascjones and me were talking at the hangout we decided to try doing [the bowling kata](http://codingdojo.org/cgi-bin/index.pl?KataBowling) to get an idea about the knowledge we might be lacking.

So the assignment for this week is the bowling kata.

**Comment by ascjones** [comment]
And maybe for the first attempt we could just get it working *without* dependent types first of all? i.e. just use ints and lists to start with? Then refactor to dependent types.

**Comment by ToJans** [comment]
Indeed! I forgot to mention that part :wink:

**Comment by gregoryyoung** [comment]
It might be good to have some people brush up on haskell as an overall
strategy towards idris.

EG for a lesson plan especially if doing it again, do some basic haskell.
Implement bowling kata in haskell then start trying to look at idris with
that as a starting point I imagine say 10 katas like this would be
reasonable as a learning exercise

On Mon, Feb 9, 2015 at 12:23 AM, Tom Janssens notifications@github.com
wrote:

> Indeed! I forgot to mention that part [image: :wink:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ToJans/idris101/issues/22#issuecomment-73435874.

## 

Studying for the Turing test
